@URL=127.0.0.1:8150
@URL=192.168.207.88:8150

### 
GET http://{{URL}}/train/waybillno?waybillno=YT2600228281270&expressCode=yuantong&token=7ZBF4Hn4n5hJLcYk HTTP/1.1

### 重新加载数据集
GET http://{{URL}}/identify/waybillno/reload